
= The System Wayfinder =

This tool is intended to help admins with navigating the command-line environment.

It provides information upon login and contextual information by directory. It helps
run tasks. 

Know how you have those tasks you only do now and then? But always forget exactly
what commands to run? And you've left notes ... somewhere. Do you remember where?

`Way` has your back here.

== Test it out ===

There is a https://github.com/robbieh/way/releases/tag/preview[preview release]
but currently only for Linux amd64 systems.

== Build and deploy it ==

For anyone else, or people wanting to hack:

You need https://github.com/babashka/babashka/releases[Babashka] for your system.
The current version of `way` is written in Clojure and runs on Babashka.

But for now `make exe` will build it and create the executable at `artifacts/way`.

And `make deploy` will copy it to `~/bin`.

== Hack on it ==

Either `bb nrepl` or `make repl` will give you a network repl. Happy Clojuring!

=== Disclaimer ===

I've put some code in to try to make this cross-platform friendly. Non-Linux
platforms are yet untested.

== Use it ==

First, put some stuff in your shell init file. You can get the stuff to add for
bash by running `way shell bash`. Then restart your shell.

Now go to that pesky project directly where you need to leave some reminders.

Create a note to show when you cd into that directory in the future with `way
edit direntry`. It'll fire up your `$VISUAL` editor so you can enter your note.

Now create a command, whatever you want it to be. Restart a service? Read the
system journal? Oh, that's a neat one. I always forget all the flags and
options. Try `way edit command journal`. You'll be back in your editor and can
put in a command line like `journalctl -u _my-unit_ --full --since yesterday`
but plug in a real unit name.

Give some details to go with that: `way edit usage journal` and enter some
descrptive text like "This shows the system journal for _my-unit_ since
yesterday and does not hide text with ellipses". You can use multiple lines.

Now behold! `way show all` will show your reminder and what the command is.

`way run journal` will invoke the journalctl command.

The best thing is when you come back to that directory in six months, `way`
will show your notes and remind you about your handy shortcut.

== Read some more ==

More details about
https://blog.nundrum.net/posts-output/2025-06-19-the-system-wayfinder/[The System Wayfinder]
can be found on my blob.
